INFO:itchat:Getting uuid of QR code.
INFO:itchat:Downloading QR code.
INFO:itchat:Please scan the QR code to log in.
INFO:itchat:Log in time out, reloading QR code.
INFO:itchat:Getting uuid of QR code.
INFO:itchat:Downloading QR code.
INFO:itchat:Please scan the QR code to log in.
INFO:itchat:Log in time out, reloading QR code.
INFO:itchat:Getting uuid of QR code.
INFO:itchat:Downloading QR code.
INFO:itchat:Please scan the QR code to log in.
INFO:itchat:Log in time out, reloading QR code.
INFO:itchat:Getting uuid of QR code.
INFO:itchat:Downloading QR code.
INFO:itchat:Please scan the QR code to log in.
INFO:itchat:Getting uuid of QR code.
INFO:itchat:Downloading QR code.
INFO:itchat:Please scan the QR code to log in.
INFO:itchat:Getting uuid of QR code.
INFO:itchat:Downloading QR code.
INFO:itchat:Please scan the QR code to log in.
INFO:itchat:Please press confirm on your phone.
INFO:itchat:Loading the contact, this may take a little while.
INFO:itchat:Login successfully as Axe
INFO:itchat:Getting uuid of QR code.
INFO:itchat:Downloading QR code.
INFO:itchat:Please scan the QR code to log in.
INFO:itchat:Please press confirm on your phone.
INFO:itchat:Loading the contact, this may take a little while.
INFO:itchat:Login successfully as Axe
INFO:werkzeug: * Running on http://0.0.0.0:666/ (Press CTRL+C to quit)
ERROR:main:Exception on /monitor [POST]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:werkzeug:127.0.0.1 - - [12/Jul/2019 11:23:54] "POST /monitor HTTP/1.1" 500 -
ERROR:main:Exception on /monitor [GET]
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "/Library/Python/2.7/site-packages/flask/app.py", line 2097, in make_response
    "The view function did not return a valid response. The"
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
INFO:werkzeug:127.0.0.1 - - [12/Jul/2019 11:24:43] "GET /monitor HTTP/1.1" 500 -
INFO:itchat:LOG OUT!
INFO:itchat:Getting uuid of QR code.
INFO:itchat:Downloading QR code.
INFO:itchat:Please scan the QR code to log in.
INFO:itchat:Loading the contact, this may take a little while.
INFO:itchat:Login successfully as Axe
INFO:werkzeug: * Running on http://0.0.0.0:666/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [12/Jul/2019 11:37:00] "GET /monitor HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [12/Jul/2019 11:37:01] "GET /monitor HTTP/1.1" 200 -
WARNING:root:wechat msg to:33333 type:error content:HelloWorld
INFO:werkzeug:127.0.0.1 - - [12/Jul/2019 11:41:35] "GET /monitor?to=33333&type=error&msg=HelloWorld HTTP/1.1" 200 -
WARNING:root:wechat msg to:33333 type:error content:FuckYou
INFO:werkzeug:127.0.0.1 - - [12/Jul/2019 11:41:50] "GET /monitor?to=33333&type=error&msg=FuckYou HTTP/1.1" 200 -
WARNING:root:wechat msg to:33333 type:error content:你好
INFO:werkzeug:127.0.0.1 - - [12/Jul/2019 11:42:12] "GET /monitor?to=33333&type=error&msg=你好 HTTP/1.1" 200 -
ERROR:wxpy.api.bot:an error occurred in <function text_reply at 0x103ba0b18>.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/wxpy/api/bot.py", line 453, in process
    ret = config.func(msg)
  File "main.py", line 37, in text_reply
    message = msg.text.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
INFO:itchat:Getting uuid of QR code.
INFO:itchat:Downloading QR code.
INFO:itchat:Please scan the QR code to log in.
INFO:itchat:Please press confirm on your phone.
INFO:itchat:Loading the contact, this may take a little while.
INFO:itchat:Login successfully as frog
INFO:werkzeug: * Running on http://0.0.0.0:666/ (Press CTRL+C to quit)
WARNING:urllib3.connectionpool:Retrying (Retry(total=29, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine('HTTP/1.1 0 -\r\n',))': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386714%7C3_679385977%7C11_679386561%7C201_1562904282%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_17b01eb269c358a21eba281fe778a662&uin=449141761&r=1562904283752&deviceid=e999006179929&sid=EyRWl5Tnl7xAS88o&_=1562904267647
WARNING:urllib3.connectionpool:Retrying (Retry(total=28, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine('HTTP/1.1 0 -\r\n',))': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386714%7C3_679385977%7C11_679386561%7C201_1562904282%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_17b01eb269c358a21eba281fe778a662&uin=449141761&r=1562904283752&deviceid=e999006179929&sid=EyRWl5Tnl7xAS88o&_=1562904267647
WARNING:urllib3.connectionpool:Retrying (Retry(total=29, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine('HTTP/1.1 0 -\r\n',))': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386716%7C3_679385977%7C11_679386561%7C201_1562904293%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_17b01eb269c358a21eba281fe778a662&uin=449141761&r=1562904294753&deviceid=e371488446577&sid=EyRWl5Tnl7xAS88o&_=1562904267649
WARNING:urllib3.connectionpool:Retrying (Retry(total=28, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine('HTTP/1.1 0 -\r\n',))': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386716%7C3_679385977%7C11_679386561%7C201_1562904293%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_17b01eb269c358a21eba281fe778a662&uin=449141761&r=1562904294753&deviceid=e371488446577&sid=EyRWl5Tnl7xAS88o&_=1562904267649
INFO:itchat:Getting uuid of QR code.
INFO:itchat:Downloading QR code.
INFO:itchat:Please scan the QR code to log in.
INFO:itchat:Loading the contact, this may take a little while.
INFO:itchat:Login successfully as frog
INFO:werkzeug: * Running on http://0.0.0.0:666/ (Press CTRL+C to quit)
WARNING:urllib3.connectionpool:Retrying (Retry(total=29, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine('HTTP/1.1 0 -\r\n',))': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386718%7C3_679385977%7C11_679386561%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_910b15c63155b102f537f2c53644cf89&uin=449141761&r=1562904504123&deviceid=e0124771054853&sid=XCsnCFTMmQS6g2l0&_=1562904502656
WARNING:urllib3.connectionpool:Retrying (Retry(total=29, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine('HTTP/1.1 0 -\r\n',))': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386719%7C3_679385977%7C11_679386561%7C201_1562904507%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_910b15c63155b102f537f2c53644cf89&uin=449141761&r=1562904510344&deviceid=e0534430682193&sid=XCsnCFTMmQS6g2l0&_=1562904502657
WARNING:urllib3.connectionpool:Retrying (Retry(total=29, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine('HTTP/1.1 0 -\r\n',))': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386723%7C3_679385977%7C11_679386561%7C201_1562904528%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_910b15c63155b102f537f2c53644cf89&uin=449141761&r=1562904528394&deviceid=e722100730134&sid=XCsnCFTMmQS6g2l0&_=1562904502661
WARNING:urllib3.connectionpool:Retrying (Retry(total=28, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine('HTTP/1.1 0 -\r\n',))': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386723%7C3_679385977%7C11_679386561%7C201_1562904528%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_910b15c63155b102f537f2c53644cf89&uin=449141761&r=1562904528394&deviceid=e722100730134&sid=XCsnCFTMmQS6g2l0&_=1562904502661
INFO:itchat:Getting uuid of QR code.
INFO:itchat:Downloading QR code.
INFO:itchat:Please scan the QR code to log in.
INFO:itchat:Please press confirm on your phone.
INFO:itchat:Loading the contact, this may take a little while.
INFO:itchat:Login successfully as frog
INFO:werkzeug: * Running on http://0.0.0.0:666/ (Press CTRL+C to quit)
WARNING:urllib3.connectionpool:Retrying (Retry(total=29, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine('HTTP/1.1 0 -\r\n',))': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386727%7C3_679385977%7C11_679386561%7C201_1562904574%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562904574481&deviceid=e753723497604&sid=Huzu7MWVX7wTfx5i&_=1562904570563
WARNING:urllib3.connectionpool:Retrying (Retry(total=28, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', BadStatusLine('HTTP/1.1 0 -\r\n',))': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386727%7C3_679385977%7C11_679386561%7C201_1562904574%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562904574481&deviceid=e753723497604&sid=Huzu7MWVX7wTfx5i&_=1562904570563
WARNING:urllib3.connectionpool:Retrying (Retry(total=29, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='webpush.wx2.qq.com', port=443): Read timed out. (read timeout=30)",)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=28, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x106bb4bd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=27, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x106bb4750>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=26, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x106bb4f10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=25, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x106bb4d10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=24, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x106bb4f50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=23, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c035d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=22, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c03090>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=21, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c03690>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=20, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c03710>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=19, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c03490>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=18, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c03910>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=17, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c03a50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=16, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c03b90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=15, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c03c90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=14, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c03dd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=13, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c03f10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=12, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c1a090>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=11, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c1a1d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=10, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c1a310>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=9, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c1a450>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=8, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c1a590>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=7, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c1a6d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=6, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x106bb4790>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=5, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c1a750>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c1a890>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c1a9d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c1ab10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c1ac50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c1ad90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608
ERROR:itchat:Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/itchat/components/login.py", line 231, in maintain_loop
    i = sync_check(self)
  File "/Library/Python/2.7/site-packages/itchat/components/login.py", line 283, in sync_check
    r = self.s.get(url, params=params, headers=headers)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/wxpy/utils/misc.py", line 351, in customized_request
    return requests.Session.request(session, method, url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='webpush.wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562905594949&deviceid=e910260234278&sid=Huzu7MWVX7wTfx5i&_=1562904570608 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c1ae90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

WARNING:urllib3.connectionpool:Retrying (Retry(total=29, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3c590>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=28, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3c710>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=27, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3c850>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=26, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3c990>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=25, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3cad0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=24, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3cc10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=23, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3cd50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=22, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3ce90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=21, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3cfd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=20, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41150>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=19, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41290>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=18, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c413d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=17, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41510>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=16, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41650>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=15, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41790>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=14, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c418d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=13, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41a10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=12, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41b50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=11, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41c90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=10, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41dd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=9, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41f10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=8, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43090>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=7, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c431d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=6, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43310>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=5, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43450>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43590>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c436d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43810>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x106a1a7d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43990>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609
ERROR:itchat:Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/itchat/components/login.py", line 231, in maintain_loop
    i = sync_check(self)
  File "/Library/Python/2.7/site-packages/itchat/components/login.py", line 283, in sync_check
    r = self.s.get(url, params=params, headers=headers)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/wxpy/utils/misc.py", line 351, in customized_request
    return requests.Session.request(session, method, url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='webpush.wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909994453&deviceid=e732356074031&sid=Huzu7MWVX7wTfx5i&_=1562904570609 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43a90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

WARNING:urllib3.connectionpool:Retrying (Retry(total=29, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3c590>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=28, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3c850>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=27, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3ca10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=26, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3cbd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=25, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3ce90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=24, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3c650>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=23, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3cc50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=22, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41110>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=21, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c413d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=20, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41590>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=19, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41750>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=18, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41a10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=17, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41bd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=16, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41d90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=15, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41050>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=14, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41690>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=13, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41cd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=12, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x106a1a7d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=11, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43110>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=10, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c432d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=9, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43590>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=8, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43750>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=7, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43950>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=6, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c430d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=5, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43710>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43c10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43d50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43e90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43fd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c26150>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610
ERROR:itchat:Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/itchat/components/login.py", line 231, in maintain_loop
    i = sync_check(self)
  File "/Library/Python/2.7/site-packages/itchat/components/login.py", line 283, in sync_check
    r = self.s.get(url, params=params, headers=headers)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/wxpy/utils/misc.py", line 351, in customized_request
    return requests.Session.request(session, method, url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='webpush.wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909995664&deviceid=e030223852676&sid=Huzu7MWVX7wTfx5i&_=1562904570610 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c26250>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

WARNING:urllib3.connectionpool:Retrying (Retry(total=29, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3c450>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=28, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3ca10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=27, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3cd50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=26, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3cf90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=25, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3c710>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=24, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3c750>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=23, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c413d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=22, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41610>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=21, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41950>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=20, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41d90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=19, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c412d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=18, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41b90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=17, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41810>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=16, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c417d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=15, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x106a1a890>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=14, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c432d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=13, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43610>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=12, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43990>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=11, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43710>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=10, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43c90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=9, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43e50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=8, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43390>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=7, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43850>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=6, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c26150>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=5, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c26290>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c263d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c26510>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c26650>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c26790>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c268d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611
ERROR:itchat:Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/itchat/components/login.py", line 231, in maintain_loop
    i = sync_check(self)
  File "/Library/Python/2.7/site-packages/itchat/components/login.py", line 283, in sync_check
    r = self.s.get(url, params=params, headers=headers)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/wxpy/utils/misc.py", line 351, in customized_request
    return requests.Session.request(session, method, url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='webpush.wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909996745&deviceid=e00481462658454&sid=Huzu7MWVX7wTfx5i&_=1562904570611 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c269d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

WARNING:urllib3.connectionpool:Retrying (Retry(total=29, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x106a1a890>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=28, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3ca10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=27, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3cdd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=26, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3ced0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=25, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3c950>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=24, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41110>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=23, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c414d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=22, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41d90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=21, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41550>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=20, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41650>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=19, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41750>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=18, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c419d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=17, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43450>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=16, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43950>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=15, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43c90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=14, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43fd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=13, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43210>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=12, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43a50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=11, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43c50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=10, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c26290>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=9, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c26450>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=8, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c26610>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=7, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c268d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=6, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c26a10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=5, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c26690>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c26b50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c26c90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c26dd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c26f10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c25090>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612
ERROR:itchat:Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/itchat/components/login.py", line 231, in maintain_loop
    i = sync_check(self)
  File "/Library/Python/2.7/site-packages/itchat/components/login.py", line 283, in sync_check
    r = self.s.get(url, params=params, headers=headers)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/wxpy/utils/misc.py", line 351, in customized_request
    return requests.Session.request(session, method, url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='webpush.wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909997811&deviceid=e586297024278&sid=Huzu7MWVX7wTfx5i&_=1562904570612 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c25190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

WARNING:urllib3.connectionpool:Retrying (Retry(total=29, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3c510>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=28, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3cdd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=27, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3c750>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=26, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c3c450>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=25, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41110>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=24, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41d90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=23, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41cd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=22, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41310>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=21, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41790>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=20, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c41e10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=19, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43950>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=18, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43d10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=17, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43850>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=16, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43c50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=15, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c43390>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=14, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c26290>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=13, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c264d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=12, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c26810>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=11, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c26690>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=10, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c26bd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=9, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c26d90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=8, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c26250>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=7, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c26110>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=6, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c26f50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=5, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c25210>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c25310>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c25450>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c25590>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c256d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c25810>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613
ERROR:itchat:Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/itchat/components/login.py", line 231, in maintain_loop
    i = sync_check(self)
  File "/Library/Python/2.7/site-packages/itchat/components/login.py", line 283, in sync_check
    r = self.s.get(url, params=params, headers=headers)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Python/2.7/site-packages/wxpy/utils/misc.py", line 351, in customized_request
    return requests.Session.request(session, method, url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='webpush.wx2.qq.com', port=443): Max retries exceeded with url: /cgi-bin/mmwebwx-bin/synccheck?synckey=1_679384822%7C2_679386733%7C3_679385977%7C11_679386561%7C201_1562904790%7C203_1562822643%7C1000_1562888716%7C1001_1562888720&skey=%40crypt_835e0fa6_f1e47bab9f448c4915890b5c1fed0a50&uin=449141761&r=1562909998861&deviceid=e691698682165&sid=Huzu7MWVX7wTfx5i&_=1562904570613 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x107c25910>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))

INFO:itchat:LOG OUT!
INFO:itchat:Getting uuid of QR code.
INFO:itchat:Downloading QR code.
INFO:itchat:Please scan the QR code to log in.
INFO:itchat:Please press confirm on your phone.
INFO:itchat:Loading the contact, this may take a little while.
INFO:itchat:Login successfully as frog
INFO:werkzeug: * Running on http://0.0.0.0:666/ (Press CTRL+C to quit)
ERROR:wxpy.api.bot:an error occurred in <function text_reply at 0x101923aa0>.
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/wxpy/api/bot.py", line 453, in process
    ret = config.func(msg)
  File "main.py", line 46, in text_reply
    print atx_nlp.nlp_func(message_dict[0])
  File "/Users/axe/WorkGit/pro/wechat_bot/atx_nlp.py", line 35, in nlp_func
    res = [ i.func_name for i in NLP_FUNC if keyword in i.func_keys ]
AttributeError: 'dict' object has no attribute 'func_keys'
INFO:itchat:Getting uuid of QR code.
INFO:itchat:Downloading QR code.
INFO:itchat:Please scan the QR code to log in.
INFO:itchat:Please press confirm on your phone.
INFO:itchat:Loading the contact, this may take a little while.
INFO:itchat:Login successfully as frog
INFO:werkzeug: * Running on http://0.0.0.0:666/ (Press CTRL+C to quit)
INFO:itchat:Getting uuid of QR code.
INFO:itchat:Downloading QR code.
INFO:itchat:Please scan the QR code to log in.
INFO:itchat:Please press confirm on your phone.
INFO:itchat:Loading the contact, this may take a little while.
INFO:itchat:Login successfully as frog
INFO:werkzeug: * Running on http://0.0.0.0:666/ (Press CTRL+C to quit)
